sudo: true
dist: xenial

language: cpp
compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y freeglut3-dev
  - sudo pip install cython

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.13.4-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.13.4-Linux-x86_64 cmake-install
  - PATH="${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH"
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cmake --version
  - cmake -Bbuild .
  - cmake --build build

